### ISSUE TITLE
Error while running docker (or normal install)

### ISSUE THREAD

**Issue by Ackia** [phglab/ALFATClust#9]
I get the error:

```
[root@d964d601fd40 data]# alfatclust

Traceback (most recent call last):
  File "/usr/local/bin/alfatclust", line 7, in <module>
    from modules.ClusterEval import eval_clusters
  File "/usr/local/bin/phglab/ALFATClust/modules/ClusterEval.py", line 2, in <module>
    from .Utils import cal_outlier_thres_by_iqr, read_seq_file_for_eval
  File "/usr/local/bin/phglab/ALFATClust/modules/Utils.py", line 4, in <module>
    from Constants import *
ModuleNotFoundError: No module named 'Constants'
```

While trying to run the software after that last update.

**Comment by jimmykhchiu** [comment]
Hi @Ackia, thanks for reporting this error, it has been fixed. Please perform a new update and the problem should be gone.
